import 'package:flutter/material.dart';
import 'package:printing/printing.dart';

import '../../../models/resume_model.dart';
import '../../../services/pdf/pdf_generator.dart';

// The live preview and the exported/shared file are generated by the exact
// same function, so what the user previews is byte-for-byte what they share.
class ResumePreviewScreen extends StatefulWidget {
  final ResumeModel resume;

  const ResumePreviewScreen({super.key, required this.resume});

  @override
  State<ResumePreviewScreen> createState() => _ResumePreviewScreenState();
}

class _ResumePreviewScreenState extends State<ResumePreviewScreen> {
  @override
  void initState() {
    super.initState();
    // PdfPreview's zoom (pinch + pan, up to 5x) only activates once a page
    // is double-tapped - there's no other on-screen affordance for it, so
    // without this hint the gesture is effectively undiscoverable.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Double-tap a page to zoom in and pinch to explore. Double-tap again to exit.'),
          duration: Duration(seconds: 4),
        ),
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    final resume = widget.resume;
    final fileName = '${resume.title.isEmpty ? 'resume' : resume.title.replaceAll(RegExp(r'[^\w\s-]'), '').trim()}.pdf';

    return Scaffold(
      appBar: AppBar(title: const Text('Resume Preview'), actions: [
        IconButton(
          tooltip: 'Edit',
          icon: const Icon(Icons.edit),
          onPressed: () => Navigator.of(context).pop(),
        ),
        IconButton(
          tooltip: 'Export PDF',
          icon: const Icon(Icons.picture_as_pdf_outlined),
          onPressed: () async {
            try {
              final bytes = await PdfGenerator.generate(resume);
              await Printing.sharePdf(bytes: bytes, filename: fileName);
            } catch (e) {
              if (!mounted) return;
              ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Failed to export PDF')));
            }
          },
        ),
      ]),
      body: PdfPreview(
        build: (format) => PdfGenerator.generate(resume),
        pdfFileName: fileName,
        canChangeOrientation: false,
        canChangePageFormat: false,
        canDebug: false,
        allowSharing: true,
        allowPrinting: true,
        useActions: true,
        loadingWidget: const Center(child: CircularProgressIndicator()),
        onError: (context, error) => Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                const Icon(Icons.error_outline, size: 40, color: Colors.redAccent),
                const SizedBox(height: 12),
                const Text('Failed to generate PDF preview', textAlign: TextAlign.center),
                const SizedBox(height: 4),
                Text('$error', textAlign: TextAlign.center, style: Theme.of(context).textTheme.bodySmall),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
